package view;

import dao.ProdutoDAO;
import java.math.BigDecimal;
import model.Produto;
import java.util.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.text.NumberFormat;
import java.util.Locale;

public class Estoque extends javax.swing.JFrame {

    private Produto objprod; // cria o v�nculo com o objaluno

    public Estoque() {
        initComponents();
        this.objprod = new Produto(); // carrega objaluno de aluno
        this.carregaTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProdutos = new javax.swing.JTable();
        b_cancelar = new javax.swing.JButton();
        b_alterar = new javax.swing.JButton();
        b_apagar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        c_nome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        c_descricao = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        c_quantidade = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        c_preco = new javax.swing.JTextField();

        setTitle("Gerenciamento de Estoque");
        setResizable(false);

        jTableProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Descrição", "Quantidade", "Preço"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableProdutosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableProdutos);
        if (jTableProdutos.getColumnModel().getColumnCount() > 0) {
            jTableProdutos.getColumnModel().getColumn(0).setMinWidth(30);
            jTableProdutos.getColumnModel().getColumn(1).setMinWidth(200);
            jTableProdutos.getColumnModel().getColumn(2).setMinWidth(30);
            jTableProdutos.getColumnModel().getColumn(3).setMinWidth(100);
        }

        b_cancelar.setText("Cancelar");
        b_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_cancelarActionPerformed(evt);
            }
        });

        b_alterar.setText("Alterar");
        b_alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_alterarActionPerformed(evt);
            }
        });

        b_apagar.setText("Apagar");
        b_apagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_apagarActionPerformed(evt);
            }
        });

        jLabel1.setText("Nome:");

        jLabel2.setText("Descrição:");

        jLabel3.setText("Quantidade: ");

        jLabel4.setText("Preço:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(c_descricao, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                            .addComponent(c_quantidade, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(c_preco)
                            .addComponent(c_nome)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(b_cancelar)
                        .addGap(18, 18, 18)
                        .addComponent(b_alterar)
                        .addGap(18, 18, 18)
                        .addComponent(b_apagar)))
                .addGap(174, 174, 174))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(c_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(c_descricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(c_quantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(c_preco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_cancelar)
                    .addComponent(b_alterar)
                    .addComponent(b_apagar))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void b_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_cancelarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_b_cancelarActionPerformed

    private void b_alterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_alterarActionPerformed

       try {
        // recebendo e validando dados da interface gráfica.
        int id = 0;
        String nome;
        String descricao;
        int quantidade;
        BigDecimal preco;

            if (this.c_nome.getText().length() < 2) {
            throw new Mensagens("Nome deve conter ao menos 2 caracteres.");
        } else {
            nome = this.c_nome.getText();
        }

        if (this.c_descricao.getText().length() < 2) {
            throw new Mensagens("Descrição deve conter ao menos 2 caracteres.");
        } else {
            descricao = this.c_descricao.getText();
        }

        if (this.c_quantidade.getText().length() <= 0) {
            throw new Mensagens("Quantidade deve ser número e maior que zero.");
        } else {
            quantidade = Integer.parseInt(this.c_quantidade.getText());
        }

        try {
            preco = new BigDecimal(this.c_preco.getText());
        } catch (Exception e) {
            throw new Mensagens("Preço inválido! Use apenas números e ponto (ex: 10.50)");
        }


          if (this.jTableProdutos.getSelectedRow() == -1) {
            throw new Mensagens("Primeiro selecione um produto para alterar.");
        } else {
            id = Integer.parseInt(this.jTableProdutos
                    .getValueAt(this.jTableProdutos.getSelectedRow(), 0)
                    .toString());
        }

            Produto produto = new Produto();
            produto.setId_produto(id);
            produto.setNome_produto(nome);
            produto.setDescricao_produto(descricao);
            produto.setQuantidade_estoque(quantidade);
            produto.setPreco(preco);

            // envia os dados para o Aluno processar
            ProdutoDAO dao = new ProdutoDAO();
            if (dao.atualizarProduto(produto)) {

            // limpar campos
           this.c_nome.setText("");
            this.c_descricao.setText("");
            this.c_quantidade.setText("");
            this.c_preco.setText("");

            JOptionPane.showMessageDialog(rootPane, "Produto atualizado com sucesso!");
        }

             } catch (Mensagens erro) {
                JOptionPane.showMessageDialog(null, erro.getMessage());
            } catch (NumberFormatException erro2) {
                JOptionPane.showMessageDialog(null, "Informe um número válido.");
            } finally {
                 carregaTabela(); // atualiza tabela
    }
        
    }//GEN-LAST:event_b_alterarActionPerformed

    private void jTableProdutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableProdutosMouseClicked

        if (this.jTableProdutos.getSelectedRow() != -1) {

            String nome = this.jTableProdutos.getValueAt(this.jTableProdutos.getSelectedRow(), 1).toString();
            String idade = this.jTableProdutos.getValueAt(this.jTableProdutos.getSelectedRow(), 2).toString();
            String curso = this.jTableProdutos.getValueAt(this.jTableProdutos.getSelectedRow(), 3).toString();
            String fase = this.jTableProdutos.getValueAt(this.jTableProdutos.getSelectedRow(), 4).toString();

            this.c_nome.setText(nome);
            this.c_descricao.setText(idade);
            this.c_quantidade.setText(curso);
            this.c_preco.setText(fase);

        }
    }//GEN-LAST:event_jTableProdutosMouseClicked

    private void b_apagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_apagarActionPerformed
        try {

        int id;

        if (this.jTableProdutos.getSelectedRow() == -1) {
            throw new Mensagens("Primeiro selecione um produto para APAGAR");
        } else {
            id = Integer.parseInt(this.jTableProdutos
                    .getValueAt(this.jTableProdutos.getSelectedRow(), 0)
                    .toString());
        }

            // retorna 0 -> primeiro bot�o | 1 -> segundo bot�o | 2 -> terceiro bot�o
           int resposta = JOptionPane.showConfirmDialog(null,
                "Tem certeza que deseja apagar este produto?");

        if (resposta == 0) { // SIM

            ProdutoDAO dao = new ProdutoDAO();
            if (dao.removerProduto(id)) {

                this.c_nome.setText("");
                this.c_descricao.setText("");
                this.c_quantidade.setText("");
                this.c_preco.setText("");
               JOptionPane.showMessageDialog(rootPane, "Produto removido com sucesso!");
            } else {
            }

            }

            System.out.println(this.objprod.getMinhaLista().toString());

        } catch (Mensagens erro) {
        JOptionPane.showMessageDialog(null, erro.getMessage());
    } finally {
        carregaTabela();
    }
    }//GEN-LAST:event_b_apagarActionPerformed

    @SuppressWarnings("unchecked")
    
private NumberFormat formatador = NumberFormat.getCurrencyInstance(new Locale("pt", "BR"));
    
@SuppressWarnings("unchecked")
    public void carregaTabela() {
        
        DefaultTableModel modelo = (DefaultTableModel) this.jTableProdutos.getModel();
        modelo.setNumRows(0);

        ProdutoDAO dao = new ProdutoDAO();
        List<Produto> produtos = dao.listarProdutos();

        // Loop para percorrer cada produto da lista
        for (Produto p : produtos) {
            
            // --- MUDANÇA 1 ---
            // Pega o número (ex: 149.90) e usa o 'formatador' para
            // transformar em texto (ex: "R$ 149,90")
            String precoFormatado = formatador.format(p.getPreco());
            
            // --- MUDANÇA 2 ---
            // Adiciona a linha na tabela, mas agora passando o 'precoFormatado'
            modelo.addRow(new Object[]{
                p.getId_produto(),
                p.getNome_produto(),
                p.getDescricao_produto(),
                p.getQuantidade_estoque(),
                precoFormatado  // <-- Aqui está a mudança!
            });
        }
}

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Estoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Estoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Estoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Estoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Estoque().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_alterar;
    private javax.swing.JButton b_apagar;
    private javax.swing.JButton b_cancelar;
    private javax.swing.JTextField c_descricao;
    private javax.swing.JTextField c_nome;
    private javax.swing.JTextField c_preco;
    private javax.swing.JTextField c_quantidade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableProdutos;
    // End of variables declaration//GEN-END:variables
}
