package view;

import dao.ProdutoDAO;
import java.math.BigDecimal;
import model.Produto;
import java.util.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.text.NumberFormat;
import java.util.Locale;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.TableModel;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Font;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfWriter;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Element;
import java.io.FileOutputStream;
import java.awt.Desktop;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;

public class Estoque extends javax.swing.JFrame {

    private Produto objprod; // cria o bjetoaluno

    public Estoque() {
        initComponents();
        this.objprod = new Produto(); // carrega objaluno de aluno
        this.carregaTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProdutos = new javax.swing.JTable();
        b_cancelar = new javax.swing.JButton();
        b_alterar = new javax.swing.JButton();
        b_apagar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        c_nome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        c_descricao = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        c_quantidade = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        c_preco = new javax.swing.JTextField();
        btnExportar = new javax.swing.JButton();

        setTitle("Gerenciamento de Estoque");
        setResizable(false);

        jTableProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Descrição", "Quantidade", "Preço", "Data de Cadastro", "Data de Alteração"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableProdutosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableProdutos);
        if (jTableProdutos.getColumnModel().getColumnCount() > 0) {
            jTableProdutos.getColumnModel().getColumn(0).setResizable(false);
            jTableProdutos.getColumnModel().getColumn(0).setPreferredWidth(30);
            jTableProdutos.getColumnModel().getColumn(1).setResizable(false);
            jTableProdutos.getColumnModel().getColumn(1).setPreferredWidth(150);
            jTableProdutos.getColumnModel().getColumn(2).setResizable(false);
            jTableProdutos.getColumnModel().getColumn(2).setPreferredWidth(100);
            jTableProdutos.getColumnModel().getColumn(3).setResizable(false);
            jTableProdutos.getColumnModel().getColumn(3).setPreferredWidth(70);
            jTableProdutos.getColumnModel().getColumn(4).setResizable(false);
            jTableProdutos.getColumnModel().getColumn(4).setPreferredWidth(50);
            jTableProdutos.getColumnModel().getColumn(5).setResizable(false);
            jTableProdutos.getColumnModel().getColumn(5).setPreferredWidth(120);
            jTableProdutos.getColumnModel().getColumn(6).setResizable(false);
            jTableProdutos.getColumnModel().getColumn(6).setPreferredWidth(120);
        }

        b_cancelar.setText("Cancelar");
        b_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_cancelarActionPerformed(evt);
            }
        });

        b_alterar.setText("Alterar");
        b_alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_alterarActionPerformed(evt);
            }
        });

        b_apagar.setText("Apagar");
        b_apagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_apagarActionPerformed(evt);
            }
        });

        jLabel1.setText("Nome:");

        jLabel2.setText("Descrição:");

        jLabel3.setText("Quantidade: ");

        jLabel4.setText("Preço:");

        btnExportar.setText("Imprimir relatório");
        btnExportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(b_cancelar)
                                .addGap(18, 18, 18)
                                .addComponent(b_alterar)
                                .addGap(18, 18, 18)
                                .addComponent(b_apagar))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(c_descricao, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(c_quantidade, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(c_preco)
                                    .addComponent(c_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(126, 126, 126)
                        .addComponent(btnExportar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 739, Short.MAX_VALUE))
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(c_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(c_descricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(c_quantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(c_preco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_cancelar)
                    .addComponent(b_alterar)
                    .addComponent(b_apagar)
                    .addComponent(btnExportar))
                .addGap(38, 38, 38))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void b_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_cancelarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_b_cancelarActionPerformed

    private void b_alterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_alterarActionPerformed

       try {
        // recebendo e validando dados da interface gráfica.
        int id = 0;
        String nome;
        String descricao;
        int quantidade;
        BigDecimal preco;

            if (this.c_nome.getText().length() < 2) {
            throw new Mensagens("Nome deve conter ao menos 2 caracteres.");
        } else {
            nome = this.c_nome.getText();
        }

        if (this.c_descricao.getText().length() < 2) {
            throw new Mensagens("Descrição deve conter ao menos 2 caracteres.");
        } else {
            descricao = this.c_descricao.getText();
        }

        if (this.c_quantidade.getText().length() <= 0) {
            throw new Mensagens("Quantidade deve ser número e maior que zero.");
        } else {
            quantidade = Integer.parseInt(this.c_quantidade.getText());
        }

        try {
            preco = new BigDecimal(this.c_preco.getText());
        } catch (Exception e) {
            throw new Mensagens("Preço inválido! Use apenas números e ponto (ex: 10.50)");
        }


          if (this.jTableProdutos.getSelectedRow() == -1) {
            throw new Mensagens("Primeiro selecione um produto para alterar.");
        } else {
            id = Integer.parseInt(this.jTableProdutos
                    .getValueAt(this.jTableProdutos.getSelectedRow(), 0)
                    .toString());
        }

            Produto produto = new Produto();
            produto.setId_produto(id);
            produto.setNome_produto(nome);
            produto.setDescricao_produto(descricao);
            produto.setQuantidade_estoque(quantidade);
            produto.setPreco(preco);

            // envia os dados pro aluno processa
            ProdutoDAO dao = new ProdutoDAO();
            if (dao.atualizarProduto(produto)) {

           this.c_nome.setText("");
            this.c_descricao.setText("");
            this.c_quantidade.setText("");
            this.c_preco.setText("");

            JOptionPane.showMessageDialog(rootPane, "Produto atualizado com sucesso!");
        }

             } catch (Mensagens erro) {
                JOptionPane.showMessageDialog(null, erro.getMessage());
            } catch (NumberFormatException erro2) {
                JOptionPane.showMessageDialog(null, "Informe um número válido.");
            } finally {
                 carregaTabela();
    }
        
    }//GEN-LAST:event_b_alterarActionPerformed

    private void jTableProdutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableProdutosMouseClicked

        if (this.jTableProdutos.getSelectedRow() != -1) {

            String nome = this.jTableProdutos.getValueAt(this.jTableProdutos.getSelectedRow(), 1).toString();
            String descricao = this.jTableProdutos.getValueAt(this.jTableProdutos.getSelectedRow(), 2).toString();
            String quantidade = this.jTableProdutos.getValueAt(this.jTableProdutos.getSelectedRow(), 3).toString();
            String preco = this.jTableProdutos.getValueAt(this.jTableProdutos.getSelectedRow(), 4).toString();

            this.c_nome.setText(nome);
            this.c_descricao.setText(descricao);
            this.c_quantidade.setText(quantidade);
            this.c_preco.setText(preco);

        }
    }//GEN-LAST:event_jTableProdutosMouseClicked

    private void b_apagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_apagarActionPerformed
        try {

        int id;

        if (this.jTableProdutos.getSelectedRow() == -1) {
            throw new Mensagens("Primeiro selecione um produto para APAGAR");
        } else {
            id = Integer.parseInt(this.jTableProdutos
                    .getValueAt(this.jTableProdutos.getSelectedRow(), 0)
                    .toString());
        }

           int resposta = JOptionPane.showConfirmDialog(null,
                "Tem certeza que deseja apagar este produto?");

        if (resposta == 0) { // SIM

            ProdutoDAO dao = new ProdutoDAO();
            if (dao.removerProduto(id)) {

                this.c_nome.setText("");
                this.c_descricao.setText("");
                this.c_quantidade.setText("");
                this.c_preco.setText("");
               JOptionPane.showMessageDialog(rootPane, "Produto removido com sucesso!");
            } else {
            }

            }

            System.out.println(this.objprod.getMinhaLista().toString());

        } catch (Mensagens erro) {
        JOptionPane.showMessageDialog(null, erro.getMessage());
    } finally {
        carregaTabela();
    }
    }//GEN-LAST:event_b_apagarActionPerformed

   

private void gerarRelatorioPDF(File file, List<Produto> listaDeDados, String tituloRelatorio) throws IOException, DocumentException {
    
    Document document = new Document(PageSize.A4.rotate(), 30, 30, 30, 30);
    PdfWriter.getInstance(document, new FileOutputStream(file));
    document.open();

    Font fonteTitulo = new Font(Font.FontFamily.HELVETICA, 18, Font.BOLD);
    Paragraph titulo = new Paragraph(tituloRelatorio, fonteTitulo);
    titulo.setAlignment(Element.ALIGN_CENTER);
    titulo.setSpacingAfter(20);
    document.add(titulo);

    PdfPTable pdfTable = new PdfPTable(5); 
    pdfTable.setWidthPercentage(100);

    String[] colunas = {"ID", "Nome", "Descrição", "Preço", "Qtd"};
    Font fonteCabecalho = new Font(Font.FontFamily.HELVETICA, 12, Font.BOLD, BaseColor.WHITE);
    
    for (String col : colunas) {
        PdfPCell cell = new PdfPCell(new Paragraph(col, fonteCabecalho));
        cell.setBackgroundColor(BaseColor.GRAY);
        cell.setHorizontalAlignment(Element.ALIGN_CENTER);
        pdfTable.addCell(cell);
    }

    Font fonteDados = new Font(Font.FontFamily.HELVETICA, 10, Font.NORMAL);
    NumberFormat formatador = NumberFormat.getCurrencyInstance(new Locale("pt", "BR"));

    for (Produto p : listaDeDados) {
        pdfTable.addCell(new Paragraph(String.valueOf(p.getId_produto()), fonteDados));
        pdfTable.addCell(new Paragraph(p.getNome_produto(), fonteDados));
        pdfTable.addCell(new Paragraph(p.getDescricao_produto(), fonteDados));
        pdfTable.addCell(new Paragraph(formatador.format(p.getPreco()), fonteDados));
        pdfTable.addCell(new Paragraph(String.valueOf(p.getQuantidade_estoque()), fonteDados));
    }

    document.add(pdfTable);
    document.close();
}
    


    private void btnExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportarActionPerformed

    Object[] opcoes = {"Geral (Tudo)", "Mensal (Últimos 30 dias)"};
    int escolha = JOptionPane.showOptionDialog(this,
            "Qual tipo de relatório deseja gerar?",
            "Tipo de Relatório",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE,
            null,
            opcoes,
            opcoes[0]);

    if (escolha == -1) return;

    List<Produto> listaParaImprimir;
    String tituloDoPDF;
    ProdutoDAO dao = new ProdutoDAO();

    if (escolha == 0) { 
        listaParaImprimir = dao.listarProdutos();
        tituloDoPDF = "Relatório Geral de Estoque";
    } else { 
        listaParaImprimir = dao.listarProdutosUltimoMes(); 
        tituloDoPDF = "Relatório Mensal (Novos Produtos)";
    }

    if (listaParaImprimir.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Não há dados para este relatório.");
        return;
    }

    JFileChooser fileChooser = new JFileChooser();
    fileChooser.setDialogTitle("Salvar PDF");
    fileChooser.setFileFilter(new FileNameExtensionFilter("Arquivos PDF (*.pdf)", "pdf"));
    fileChooser.setSelectedFile(new File("relatorio.pdf"));

    int userSelection = fileChooser.showSaveDialog(this);

    if (userSelection == JFileChooser.APPROVE_OPTION) {
        File fileToSave = fileChooser.getSelectedFile();
        if (!fileToSave.getAbsolutePath().endsWith(".pdf")) {
            fileToSave = new File(fileToSave.getAbsolutePath() + ".pdf");
        }

        try {
          
            gerarRelatorioPDF(fileToSave, listaParaImprimir, tituloDoPDF);
            
            int abrir = JOptionPane.showConfirmDialog(this, "Sucesso! Abrir arquivo?", "Fim", JOptionPane.YES_NO_OPTION);
            if (abrir == JOptionPane.YES_OPTION) {
                Desktop.getDesktop().open(fileToSave);
            }
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Erro: " + ex.getMessage());
        }
    }
    }//GEN-LAST:event_btnExportarActionPerformed

    @SuppressWarnings("unchecked")
    
private NumberFormat formatador = NumberFormat.getCurrencyInstance(new Locale("pt", "BR"));
    
@SuppressWarnings("unchecked")
    public void carregaTabela() {
        
        DefaultTableModel modelo = (DefaultTableModel) this.jTableProdutos.getModel();
        modelo.setNumRows(0);

        ProdutoDAO dao = new ProdutoDAO();
        List<Produto> produtos = dao.listarProdutos();

        for (Produto p : produtos) {
  
            String precoFormatado = formatador.format(p.getPreco());
            
         DateTimeFormatter f = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss");

            LocalDateTime dataFormatadac = p.getData_cadastro()
            .toInstant()
            .atZone(ZoneId.of("America/Sao_Paulo")) // corrige o fuso
            .toLocalDateTime();
            String dataExibidac = dataFormatadac.format(f);
            
             String dataExibidaa;

if (p.getData_alteracao() != null) {
    LocalDateTime dataAlt = p.getData_alteracao().toInstant()
            .atZone(ZoneId.of("America/Sao_Paulo"))
            .toLocalDateTime();

    dataExibidaa = dataAlt.format(f);
} else {
    dataExibidaa = "";
}

            modelo.addRow(new Object[]{
                p.getId_produto(),
                p.getNome_produto(),
                p.getDescricao_produto(),
                p.getQuantidade_estoque(),
                precoFormatado,
                dataExibidac,
                dataExibidaa
            });
        }
}

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Estoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Estoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Estoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Estoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Estoque().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_alterar;
    private javax.swing.JButton b_apagar;
    private javax.swing.JButton b_cancelar;
    private javax.swing.JButton btnExportar;
    private javax.swing.JTextField c_descricao;
    private javax.swing.JTextField c_nome;
    private javax.swing.JTextField c_preco;
    private javax.swing.JTextField c_quantidade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableProdutos;
    // End of variables declaration//GEN-END:variables
}
