package view;

import javax.swing.JOptionPane;

public class TelaCadastrarProduto extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaCadastrarProduto.class.getName());

    /**
     * Creates new form TelaCadastrarNovoProduto
     */
    public TelaCadastrarProduto() {
        initComponents();
        jComboCategoria.removeAllItems();
    jComboCategoria.addItem("Selecione...");
    jComboCategoria.addItem("Bebidas");
    jComboCategoria.addItem("Comidas");
    
    jLabelProduto.setVisible(false);
    jComboProduto.setVisible(false); // começa invisível

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboCategoria = new javax.swing.JComboBox<>();
        jComboProduto = new javax.swing.JComboBox<>();
        jLabelCategoria = new javax.swing.JLabel();
        jLabelProduto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastrar Produto");
        setResizable(false);

        jComboCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione...", "1 - Bebidas", "2 - Comidas" }));
        jComboCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboCategoriaActionPerformed(evt);
            }
        });

        jComboProduto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione...", " " }));

        jLabelCategoria.setText("Categoria:");

        jLabelProduto.setText("Produto:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboCategoria, 0, 210, Short.MAX_VALUE)
                    .addComponent(jLabelCategoria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboProduto, 0, 210, Short.MAX_VALUE)
                    .addComponent(jLabelProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCategoria)
                    .addComponent(jLabelProduto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(368, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboCategoriaActionPerformed
        String categoriaSelecionada = (String) jComboCategoria.getSelectedItem();

// Limpa o jComboBoxProduto
jComboProduto.removeAllItems();

// Se nenhuma categoria válida foi selecionada, esconde o combo de produtos
if (categoriaSelecionada == null || categoriaSelecionada.equals("Selecione...")) {
    jComboProduto.setVisible(false);
    jLabelProduto.setVisible(false);
    return;
}

// Mostra o combo de produtos
jComboProduto.setVisible(true);
jLabelProduto.setVisible(true);

// Preenche conforme a categoria escolhida
if (categoriaSelecionada.equals("Bebidas")) {
     jComboProduto.addItem("Selecione...");
    jComboProduto.addItem("Coca-Cola");
    jComboProduto.addItem("Suco");
    jComboProduto.addItem("Água");
} else if (categoriaSelecionada.equals("Comidas")) {
     jComboProduto.addItem("Selecione...");
    jComboProduto.addItem("Pizza");
    jComboProduto.addItem("Salgado");
    jComboProduto.addItem("Hambúrguer");
}
    }//GEN-LAST:event_jComboCategoriaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaCadastrarProduto().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboCategoria;
    private javax.swing.JComboBox<String> jComboProduto;
    private javax.swing.JLabel jLabelCategoria;
    private javax.swing.JLabel jLabelProduto;
    // End of variables declaration//GEN-END:variables
}
